runtime: python39

env_variables:
  FLASK_ENV: production
  SECRET_KEY: "your-production-secret-key-here"
  DATABASE_URL: "sqlite:///lawn_care.db"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always 